### ISSUE TITLE
error: failed to run custom build command for `openssl-sys v0.9.78` (Ubuntu)

### ISSUE THREAD

**Issue by shidokamo** [InternetMaximalism/intmax-rollup-cli#23]
I got following error when I run `cargo buile -release` on Ubuntu 20.04.

```
error: failed to run custom build command for `openssl-sys v0.9.78`
                                           
Caused by:                                                                             
  process didn't exit successfully: `/home/shidokamo/intmax-rollup-cli/target/release/build/openssl-sys-d698e8ba1f4afc3d/build-script-main` (exit status: 101)   
```

It seems that this is a typical Rust issue on Ubuntu. 
It was resolved by installing following packages. 

```
sudo apt-get install -y pkg-config libssl-dev
```

I think it's good to add some note on README so that people who is not familar with Rust user can try it smoothly.

**Comment by hrmk1o3** [comment]
Thank you for trying this CLI. Please check the updated documentation.

**Comment by shidokamo** [comment]
That's awesome. Thank you!
