### ISSUE TITLE
tx command accepted --receiver-address 0x  

### ISSUE THREAD

**Issue by harukataro** [InternetMaximalism/intmax-rollup-cli#25]
Below is my observation with cli. "0x"  is meaningless I feel. 

-------------------------------------------------------
~ % intmax tx send --receiver-address 0x -i 0xaa --amount 1 
WARNING: DO NOT interrupt execution of this program while a transaction is being sent.
start proving: user_tx_proof
prove: 1.925 sec
transaction hash is 0xf222ab6c4aac70e327133ca8bfddeff9dcdd0c4ea73250e2e40fc557e09de972
broadcast transaction successfully
start proving: received_signature
prove: 0.023 sec
send received signature successfully

**Comment by hrmk1o3** [comment]
Thank you for trying this CLI. Until now, if a short-length address was given, it was filled with zeros until it reached the correct size. To reduce the number of typos in the receiver address, the receiver address now requires a full-sized hex string.

**Comment by harukataro** [comment]
Thank you for explanation. And thank you for update setting uodate.
