### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by codecD7** [InternetMaximalism/intmax-rollup-cli#36]
While running the command on Windows:
intmax config aggregator-url https://prealpha.testnet.intmax.io/

This is the error I get:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 183, kind: AlreadyExists, message: "Cannot create a file when that file already exists." }', src\controller\mod.rs:263:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by hrmk1o3** [comment]
Thank you for your report.
Please try to delete `.intmax` directory under the home directory and try it again.
There are some new updates, please check there as well.

**Comment by codecD7** [comment]
Sure, will update if I face any issues.
