### ISSUE TITLE
Installation guide Ubuntu, last step url error

### ISSUE THREAD

**Issue by mrchenmo** [InternetMaximalism/intmax-rollup-cli#38]
![J6% 5TS8E9$%OMN45UNGSJB](https://user-images.githubusercontent.com/18020929/231337938-d6570ee9-4ffa-4909-a4be-4a1167bd91e0.png)
Using this url will prompt an error
Should be modified to https://alpha.testnet.intmax.io/

**Comment by hrmk1o3** [comment]
Thank you for your report.
I fix it now.
