### ISSUE TITLE
docs : wrong asset list command

### ISSUE THREAD

**Issue by SvenMeyer** [InternetMaximalism/intmax-rollup-cli#42]
On page
[https://docs.testnet.intmax.io/getting-started/interface-guide#display-assets](https://docs.testnet.intmax.io/getting-started/interface-guide#display-assets)
it says 

Displays all currently owned assets. However, assets that have not yet been merged are not counted.
`intmax assets`

However the command should be `intmax account assets`

**Comment by hrmk1o3** [comment]
Thank you for your report. The interface guide is currently not updated; please check README directly.
