### ISSUE TITLE
error when running register

### ISSUE THREAD

**Issue by notthinks** [InternetMaximalism/intmax-rollup-cli#45]
command

`intmax io register --network scroll --maker-amount 1 --receiver-address carol --taker-amount 1000000000000000`

errors like this

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexCharacter { c: 'x', index: 1 }', /root/intmax-rollup-cli/src/controller/mod.rs:1106:70                                                         note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by hrmk1o3** [comment]
Thank you for your report.

Try the environment variable `PRIVATE_KEY` without 0x-prefix.
